import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Form from "@/components/form";
import Header from "@/components/header";
import Footer from "@/components/footer"
import Characters from "@/components/characters";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  
  return (
    <>
      <Head>
        <title>CineIDE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Rammetto+One&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Cairo&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Header></Header>
      </header>

      <div className={styles.grid} id="catalogo">
        {Array.from({ length: 16 }, (_, i) => (
          <img
            key={i}
            // Pôsters no diretório posters
            src={`/posters/${i + 1}.png`}
            alt={`Poster ${i + 1}`}
            className={styles.poster}
          />
        ))}
      </div>

      <main className={styles.main}>
        
        <div className={styles.characters}>
          <Characters></Characters>
        </div>

        <div className={styles.form}>
          <Form></Form>
        </div>

      </main>
      
      
      <footer className={styles.footer}/>   
      <Footer></Footer>       
    </>
  );
}
